MyAutomovil/MVC/Controllers/AutenticarEnElSistemaController.cs
using Fachada;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class AutenticarEnElSistemaController : Controller
    {
        private Dominio.LogicaDelNegocio.AutenticarEnElSistema _autenticarEnElSistema;

        public AutenticarEnElSistemaController()
        {
            _autenticarEnElSistema = new Dominio.LogicaDelNegocio.AutenticarEnElSistema();
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(IndexViewModel usuarioNuevo)
        {
            if (usuarioNuevo.user == null)
            {
                ViewData["MensajeUsuario"] = "Campo obligatorio";
                return View();
            }
            Dominio.EntidadesDominio.Usuario entidadUsuario = new Dominio.EntidadesDominio.Usuario
            {
                user = usuarioNuevo.user,
                contraseña = usuarioNuevo.contraseña
            };
            Boolean bandera = _autenticarEnElSistema.AutenticarUsuario(entidadUsuario.user, entidadUsuario.contraseña);
            if (bandera == true)
            {
                return RedirectToAction("../RegistrarVehiculo/ConsultarVehiculo", new { tipo = entidadUsuario.tipo });
            }
            else
            {
                ViewData["MensajeLogueo"] = "Usuario o contraseña incorrecta";
                return View();
            }
        }

        public ActionResult RecuperarContraseña()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RecuperarContraseña(RecuperarContraseñaModel cambioContraseña)
        {
            if(cambioContraseña.user == null)
            {
                ViewData["MensajeUsuario"] = "Campo obligatorio";
                return View();
            }
            if(cambioContraseña.contraseña == cambioContraseña.contraseña2)
            {
                Dominio.EntidadesDominio.Usuario entidadUsuario = new Dominio.EntidadesDominio.Usuario
                {
                    user = cambioContraseña.user,
                    contraseña = cambioContraseña.contraseña
                };
                Boolean bandera = _autenticarEnElSistema.RecuperarContraseña(entidadUsuario.user, entidadUsuario.contraseña);
                if (bandera == true)
                {
                    return RedirectToAction("/AutenticarseEnElSistema/Index", new { tipo = entidadUsuario.tipo });
                }
                else
                {
                    ViewData["MensajeLogueo"] = "Error en el ingreso de datos";
                    return View();
                }
            }
            else
            {
                ViewData["MensajeLogueo"] = "Ambas contraseñas deben ser iguales";
                return View();
            }
        }
    }
}

MyAutomovil/MVC/Controllers/RegistrarEmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.Models;

namespace MVC.Controllers
{
    public class RegistrarEmpleadoController : Controller
    {
        // GET: RegistrarEmpleado
        public ActionResult AdicionarEmpleado()
        {
            return View();
        }

        public ActionResult ActualizarEmpleado()
        {
            return View();
        }

        public ActionResult ConsultarEmpleado()
        {
            return View();
        }
        
        public PartialViewResult RecuperarEmpleados() {
            MVC.Models.FachadaW f = new MVC.Models.FachadaW();
            return PartialView("_Empleados",f.RecuperarEmpleados());
        }

        public ActionResult ConsultarEmpleado2() {
            return View();
        }

        public ActionResult ConsultarEmpleado3()
        {
            return View();
        }
    }
}

MyAutomovil/MVC/Controllers/RegistrarMarcaController.cs
using Fachada;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dominio.EntidadesDominio;
using MVC.Models;

namespace MVC.Controllers
{
    public class RegistrarMarcaController : Controller
    {
        private Dominio.LogicaDelNegocio.RegistrarMarca _registrarMarca;

        public RegistrarMarcaController()
        {
            _registrarMarca = new Dominio.LogicaDelNegocio.RegistrarMarca();
        }

        public ActionResult AdicionarMarca()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AdicionarMarca(AdicionarMarcaViewModel AdicionarMarca)
        {
            if (AdicionarMarca.nombreMarca == null)
            {
                ViewData["MensajeMarca"] = "Campo obligatorio";
                return View();
            }

            if (AdicionarMarca.pais == null)
            {
                ViewData["MensajePais"] = "Campo obligatorio";
                return View();
            }

            Dominio.EntidadesDominio.Marca Marca = new Dominio.EntidadesDominio.Marca
            {
                nombreMarca = AdicionarMarca.nombreMarca,
                pais = AdicionarMarca.pais
            };
            if(_registrarMarca.AdicionarMarca(Marca.nombreMarca, Marca.pais))
            {

                ViewData["MensajeExito"] = "Exito en la creacion de marca";
                return View();
            }
            else
            {
                ViewData["MensajeIngreso"] = "Error al adicionar marca";
                return View();
            }
            
            
        }

        public ActionResult ActualizarMarca(string nombreMarca)
        {
            nombreMarca = "Amet Industries";
            var entidadMarca = _registrarMarca.ConsultarMarca(nombreMarca);
            ActualizarMarcaViewModel ActualizarMarcaVm = new ActualizarMarcaViewModel
            {
                nombreMarca = entidadMarca.nombreMarca,
                pais = entidadMarca.pais
            };
            return View(ActualizarMarcaVm);
        }

        [HttpPost]
        public ActionResult ActualizarMarca(ActualizarMarcaViewModel nuevaMarca)
        {
            if (nuevaMarca.nombreMarca == null)
            {
                ViewData["MensajeMarca"] = "Campos obligatorios";
                return View();
            }
            else if (nuevaMarca.pais == null)
            {
                ViewData["MensajePais"] = "Campos obligatorios";
                return View();
            }
            Dominio.EntidadesDominio.Marca marca = new Dominio.EntidadesDominio.Marca
            {
                nombreMarca = nuevaMarca.nombreMarca,
                pais = nuevaMarca.pais
            };
            if (_registrarMarca.ActualizarMarca(marca.nombreMarca, marca.pais))
            {
                return RedirectToAction("ConsultarMarca");
            }
            else
            {
                ViewData["MensajeError"] = "Error al actualizar la marca";
                return View();
            }
        }

        public ActionResult ConsultarMarca()
        {
            return View();
        }

        public PartialViewResult ConsultarMarcaF()
        {
            FachadaW f = new FachadaW();
            return PartialView("_Marcas", f.ConsultarMarca());
        }

        [HttpPost]
        public PartialViewResult ConsultarMarcaF(string marcaId)
        {
            List<Marca> l = new List<Marca>();
            FachadaW f = new FachadaW();
            l.Add(f.ConsultarMarca(marcaId));
            return PartialView("_Marcas",l );
        }
    }
}

MyAutomovil/MVC/Controllers/RegistrarModeloController.cs
using Fachada;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class RegistrarModeloController : Controller
    {
        private Dominio.LogicaDelNegocio.RegistrarModelo _registrarModelo;

        public RegistrarModeloController()
        {
            _registrarModelo = new Dominio.LogicaDelNegocio.RegistrarModelo();
        }

        public ActionResult AdicionarModelo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AdicionarModelo(AdicionarModeloViewModelo AdicionarModelo)
        {
            if (AdicionarModelo.nombreMarca == null)
            {
                ViewData["MensajeMarca"] = "Campo obligatorio";
                return View();
            }

            if (AdicionarModelo.nombreModelo == null)
            {
                ViewData["MensajeModelo"] = "Campo obligatorio";
                return View();
            }

            if (AdicionarModelo.numeroPuertas == null)
            {
                ViewData["MensajePuertas"] = "Campo obligatorio";
                return View();
            }

            if (AdicionarModelo.cilindraje == null)
            {
                ViewData["MensajeCilindraje"] = "Campo obligatorio";
                return View();
            }

            if (AdicionarModelo.transmision == null)
            {
                ViewData["MensajeTransmision"] = "Campo obligatorio";
                return View();
            }

            Dominio.EntidadesDominio.Modelo Modelo = new Dominio.EntidadesDominio.Modelo
            {
                nombreMarca = AdicionarModelo.nombreMarca,
                nombreModelo = AdicionarModelo.nombreModelo,
                numeroPuertas = AdicionarModelo.numeroPuertas,
                cilindraje=AdicionarModelo.cilindraje,
                transmision=AdicionarModelo.transmision


            };


            if (_registrarModelo.AdicionarModelo(Modelo.nombreModelo,Modelo.nombreMarca,Modelo.numeroPuertas,Modelo.cilindraje,Modelo.transmision))
            {

                ViewData["MensajeExito"] = "Exito en la creacion de modelo";
                return View();
            }
            else
            {
                ViewData["MensajeIngreso"] = "Error al adicionar modelo";
                return View();
            }


        }


        public ActionResult ActualizarModelo(string nombreMarca, string nombreModelo)
        {
            nombreMarca = "Commodo LLC";
            nombreModelo = "cx5";
            var entidadModelo = _registrarModelo.ConsultarModelo(nombreModelo, nombreMarca);
            ActualizarModeloViewModel ActualizarModeloVm = new ActualizarModeloViewModel
            {
                nombreMarca = entidadModelo.nombreMarca,
                nombreModelo = entidadModelo.nombreModelo,
                transmision = entidadModelo.transmision,
                numeroPuertas = entidadModelo.numeroPuertas,
                cilindraje = entidadModelo.cilindraje
            };
            return View(ActualizarModeloVm);
        }

        [HttpPost]
        public ActionResult ActualizarModelo(ActualizarModeloViewModel nuevaModelo)
        {
            if (nuevaModelo.nombreMarca == null)
            {
                ViewData["MensajeMarca"] = "Campos obligatorios";
                return View();
            }
            else if (nuevaModelo.nombreModelo == null)
            {
                ViewData["MensajeModelo"] = "Campos obligatorios";
                return View();
            }
            else if (nuevaModelo.transmision == null)
            {
                ViewData["MensajeModelo"] = "Campos obligatorios";
                return View();
            }
            else if (nuevaModelo.numeroPuertas == null)
            {
                ViewData["MensajeNumero"] = "Campos obligatorios";
                return View();
            }
            else if (nuevaModelo.cilindraje == null)
            {
                ViewData["MensajeCilindraje"] = "Campos obligatorios";
                return View();
            }
            Dominio.EntidadesDominio.Modelo modelo = new Dominio.EntidadesDominio.Modelo
            {
                nombreMarca = nuevaModelo.nombreMarca,
                nombreModelo = nuevaModelo.nombreModelo,
                transmision = nuevaModelo.transmision,
                numeroPuertas = nuevaModelo.numeroPuertas,
                cilindraje = nuevaModelo.cilindraje
            };
            if (_registrarModelo.ActualizarModelo(modelo.nombreModelo, modelo.nombreMarca, modelo.numeroPuertas, modelo.cilindraje, modelo.transmision))
            {
                return RedirectToAction("ConsultarModelo");
            }
            else
            {
                ViewData["MensajeError"] = "Error al actualizar la modelo";
                return View();
            }
        }

        public ActionResult ConsultarModelo()
        {
            return View();
        }
    }
}

MyAutomovil/MVC/Controllers/RegistrarVehiculoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.Models;
using Fachada;

namespace MVC.Controllers
{
    public class RegistrarVehiculoController : Controller
    {
        // GET: RegistrarVehiculo
        public ActionResult AdicionarVehiculo()
        {
            return View();
        }

        public ActionResult ActualizarVehiculo()
        {
            return View();
        }

        public ActionResult ConsultarVehiculo()
        {
            return View();
        }

        public PartialViewResult ConsultarVehiculoF()
        {
            FachadaW f = new FachadaW();
            return PartialView("_Vehiculos",f.ConsultarVehiculo());
        }
    }
}

MyAutomovil/MVC/Views/RegistrarMarca/ActualizarMarca.cshtml
@model Fachada.ActualizarMarcaViewModel

<!DOCTYPE html>

<head>
    <title>Actualizar marca</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/styles.css" rel="stylesheet" type="text/css" />
</head>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<body style="background-color: #ffffff">
    <nav class="navbar navbar-expand-md  navbar-dark" style="background-color: rgb(0, 0, 0);">
        <a class="navbar-brand" href="#">Registrar marca</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
            </ul>
        </div>
    </nav>
    <br />
    <br />
    <div class="container">
        <div>
            <div class="row">
                <div class="col-sm-12" align="center">
                    <h2>Actualizar marca</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                    <form class="form-horizontal">
                        <fieldset>
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="nombreMarca">Nombre</label>
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="col-sm-12">
                                    @Html.EditorFor(model => model.nombreMarca, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.nombreMarca, "", new { @class = "text-danger" })
                                </div>
                                @{
                                    if (@ViewData["MensajeMarca"] != null)
                                    {
                                        <p class="alert alert-danger"> @ViewData["MensajeMarca"]</p>
                                    }
                                }
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="paisMarca">Pais</label>
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="col-sm-12">
                                    @Html.EditorFor(model => model.pais, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.pais, "", new { @class = "text-danger" })
                                </div>
                                @{
                                    if (@ViewData["MensajePais"] != null)
                                    {
                                        <p class="alert alert-danger"> @ViewData["MensajePais"]</p>
                                    }
                                }
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            </div>
                        </fieldset>
                        <br />
                        <br />
                        <div class="row">
                            <input type="submit" class="btn btn-success col-md-4" value="Guardar" />
                            <div class="col-md-4"><br /></div>
                            <button type="button" class="btn btn-danger col-md-4 ">@Html.ActionLink("Cancelar", "ConsultarMarca", null, new { @class = "myclass" })</button>
                        </div>
                    </form>
                </div>
                <div class="col-sm-3"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            @{
                if (@ViewData["MensajeError"] != null)
                {
                    <p class="alert alert-danger"> @ViewData["MensajeError"]</p>
                }
            }
        </div>
    </div>
    <div class="col-sm-3"></div>
</body>
        <br />
        <br />
        <footer class="footer" style="background-color: #000000; color: #fafafa">
            <div>
                <br />
                <br />
                <p>© WYMAN SOLUTION 2019</p>
                <br />
                <br />
            </div>
        </footer>
    
}

MyAutomovil/MVC/Views/RegistrarMarca/AdicionarMarca.cshtml
@model Fachada.AdicionarMarcaViewModel 


<!DOCTYPE html>


<head>
    <title>Adicionar marca</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/styles.css" rel="stylesheet" type="text/css" />
</head>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<body style="background-color: #ffffff">
    <nav class="navbar navbar-expand-md  navbar-dark" style="background-color: rgb(0, 0, 0);">
        <a class="navbar-brand" href="#">Registrar marca</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
            </ul>
        </div>
    </nav>
    <br />
    <br />
    <div class="container">
        <div>
            <div class="row">
                <div class="col-sm-12" align="center">
                    <h2>Adicionar marca</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                    <form class="form-horizontal">
                        <fieldset>
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="nombreMarca">Nombre</label>
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                <div class="col-sm-12">
                                    @Html.EditorFor(model => model.nombreMarca, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.nombreMarca, "", new { @class = "text-danger" })
                                </div>
                                @{
                                    if (@ViewData["MensajeMarca"] != null)
                                    {
                                        <p class="alert alert-danger"> @ViewData["MensajeMarca"]</p>
                                    }
                                }
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <label class="col-md-4 control-label" for="paisMarca">Pais</label>
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                <div class="col-sm-12">
                                    @Html.EditorFor(model => model.pais, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.pais, "", new { @class = "text-danger" })
                                </div>
                                @{
                                    if (@ViewData["MensajePais"] != null)
                                    {
                                        <p class="alert alert-danger"> @ViewData["MensajePais"]</p>
                                    }
                                }
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            </div>

                        </fieldset>
                        <br />
                        <br />
                        <div class="row">
                            <input type="submit" class="btn btn-success col-md-4" value="Guardar " />
                            <div class="col-md-4"><br /></div>
                            <button type="button" class="btn btn-danger col-md-4 ">@Html.ActionLink("Cancelar", "ConsultarMarca", null, new { @class = "myclass" })</button>
                        </div>
                    </form>
                </div>
                <div class="col-sm-3"></div>
            </div>
        </div>
    </div>
    <br />
    <br />
    <<div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            @{
                if (@ViewData["MensajeIngreso"] != null)
                {
                    <p class="alert alert-danger"> @ViewData["MensajeIngreso"]</p>
                }
            }
            @{
                if (@ViewData["MensajeExito"] != null)
                {
                    <p class="btn-success"> @ViewData["MensajeExito"]</p>
                }
            }
        </div>
    </div>
    <div class="col-sm-3"></div>
</body>
        <br />
        <br />
        <footer class="footer" style="background-color: #000000; color: #fafafa">
            <div>
                <br />
                <br />
                <p>© WYMAN SOLUTION 2019</p>
                <br />
                <br />
            </div>
        </footer>
    
}

MyAutomovil/MVC/Views/RegistrarMarca/ConsultarMarca.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<head>
    <title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <link href="~/css/styles.css" rel="stylesheet" type="text/css" />

</head>
<body>
    <nav class="navbar navbar-expand-md  navbar-dark" style="background-color: rgb(0, 0, 0);">
        <a class="navbar-brand" href="#">Registrar Vehiculo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <span class="nav-link mb-2" style="color:white;">@Html.ActionLink("Login", "Index", "AutenticarEnElSistema", null, new { style = "color:white;" })</span>
                </li>
                <li class="nav-item">
                    <span class="nav-link mb-2" style="color:white;">@Html.ActionLink("Registrar Cliente", "ConsultarCliente", "RegistrarCliente", null, new { style = "color:white;" })</span>
                </li>
                <li class="nav-item">
                    <span class="nav-link mb-2" style="color:white;">@Html.ActionLink("Registrar Concesionario", "ConsultarConcesionario", "RegistrarConcesionario", null, new { style = "color:white;" })</span>
                </li>
                <li class="nav-item">
                    <span class="nav-link mb-2" style="color:white;">@Html.ActionLink("Registrar Empleado", "ConsultarEmpleado", "RegistrarEmpleado", null, new { style = "color:white;" })</span>
                </li>
                <li class="nav-item">
                    <span class="nav-link mb-2" style="color:white;">@Html.ActionLink("Registrar Marca", "ConsultarMarca", "RegistrarMarca", null, new { style = "color:white;" })</span>
                </li>
                <li class="nav-item">
                    <span class="nav-link mb-2" style="color:white;">@Html.ActionLink("Registrar Modelo", "ConsultarModelo", "RegistrarModelo", null, new { style = "color:white;" })</span>
                </li>
                <li class="nav-item">
                    <span class="nav-link mb-2" style="color:white;">@Html.ActionLink("Registrar Vehiculo", "ConsultarVehiculo", "RegistrarVehiculo", null, new { style = "color:white;" })</span>
                </li>
            </ul>
        </div>
    </nav>
    <br>
    <br>
    <div class="container">
        <div class="row">
            <div align="center" class="col-sm-12">
                <h2> Consultar Marca</h2>
            </div>
        </div>
    </div>
    <br>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-6">
                @using (Ajax.BeginForm("ConsultarMarcaF", new AjaxOptions()
                {
                    HttpMethod = "POST",
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "contenedorMarcas"
                }))
                {
                    <form class="form-inline">
                        <input class="form-control mb-2 mr-sm-2" placeholder="Ingrese su consulta " size="40" name="marcaId" />
                        <button type="button" class="btn btn-success mb-2 ">
                            <span class="fi-icon-name" title="icon name" aria-hidden="true"></span>Consultar
                        </button>
                    </form>
                }
            </div>
            <div class="col-sm-4 btn-group-inline">
                <button type="button" class="btn btn-dark mb-2 ">
                    @Ajax.ActionLink("Listar Todos", "ConsultarMarcaF", new AjaxOptions()
                           {
                               HttpMethod = "GET",
                               InsertionMode = InsertionMode.Replace,
                               UpdateTargetId = "contenedorMarcas",
                           })
                </button>
                <button type="button" class="btn btn-success mb-2 ">@Html.ActionLink("Adicionar", "AdicionarMarca", null, new { @class = "myclass" })</button>
            </div>
        </div>
    </div>
    <div class="container" id="contenedorMarcas">

    </div>
    <br />
    <br />
    <footer class="footer" style="background-color: #000000; color: #fafafa">
        <div>
            <br />
            <br />
            <p>© WYMAN SOLUTION 2019</p>
        </div>
    </footer>
</body>
</html>